// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/career-home/CleanProfessional.tsx": () => import("../components/mockups/career-home/CleanProfessional.tsx"),
  "./components/mockups/career-home/ConversationalSetup.tsx": () => import("../components/mockups/career-home/ConversationalSetup.tsx"),
  "./components/mockups/career-home/DarkPro.tsx": () => import("../components/mockups/career-home/DarkPro.tsx"),
  "./components/mockups/career-home/GradientHero.tsx": () => import("../components/mockups/career-home/GradientHero.tsx"),
  "./components/mockups/career-home/GuidedStepper.tsx": () => import("../components/mockups/career-home/GuidedStepper.tsx"),
  "./components/mockups/career-home/ReadinessMeter.tsx": () => import("../components/mockups/career-home/ReadinessMeter.tsx"),
  "./components/mockups/career-home/WarmMinimal.tsx": () => import("../components/mockups/career-home/WarmMinimal.tsx"),
  "./components/mockups/focus-selector/ColorDotGrid.tsx": () => import("../components/mockups/focus-selector/ColorDotGrid.tsx"),
  "./components/mockups/focus-selector/PillTabs.tsx": () => import("../components/mockups/focus-selector/PillTabs.tsx"),
  "./components/mockups/focus-selector/TypographicInitials.tsx": () => import("../components/mockups/focus-selector/TypographicInitials.tsx"),
  "./components/mockups/scorecard/DarkHero.tsx": () => import("../components/mockups/scorecard/DarkHero.tsx"),
  "./components/mockups/scorecard/EditorialFlow.tsx": () => import("../components/mockups/scorecard/EditorialFlow.tsx"),
  "./components/mockups/scorecard/GradientArc.tsx": () => import("../components/mockups/scorecard/GradientArc.tsx"),
  "./components/mockups/scorecard/Newspaper.tsx": () => import("../components/mockups/scorecard/Newspaper.tsx"),
  "./components/mockups/scorecard/ReportSidebar.tsx": () => import("../components/mockups/scorecard/ReportSidebar.tsx"),
  "./components/mockups/scorecard/Timeline.tsx": () => import("../components/mockups/scorecard/Timeline.tsx")
};
